---

- hosts: all
  become: no
  gather_facts: no

  tasks:
  - name: get all the installed softwares
    win_shell: 'Get-ItemProperty "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*"| select-object DisplayName, Publisher, UninstallString, DisplayVersion | Format-List'
    register: out

  - name: debug
    debug:
      var: out
